### ISSUE TITLE
This will soon stop working

### ISSUE THREAD

**Issue by geira** [hennumjr/MetNoPy#2]
Hi, just a warning that the WSklima service from MET Norway will soon be terminated. It has been replaced with a new service called [Frost](https://frost.met.no/index.html) which delivers observation and climate data in JSON format.

Also, the name of this library may cause some confusion since WSklima/Frost are just two of many APIs delivered by MET Norway. Most of our forecast data are available at [api.met.no](https://api.met.no/), while a complete list of downloadable products should be available [here](https://www.met.no/en/free-meteorological-data/Download-services).

**Comment by andehen** [comment]
A while ago, but thanks for your update! The readme is updated. Will check out your new api whenever I have time.
